name: ecommerce
description: One stop Ecommerce solutions -  Dataviv Technologies

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.30
  share: ^0.6.4+5
  basic_utils: ^1.2.0
  pin_input_text_field: ^3.0.5
  flutter_facebook_login: ^3.0.0
  firebase_core: ^0.4.1+3
  firebase_auth: ^0.14.0+8
  timeline_tile: ^0.1.2
  sqflite: ^1.3.1
  content_placeholder: ^0.1.0
  custom_horizontal_calendar: ^0.1.3
  carousel_slider: ^1.4.1
  font_awesome_flutter: ^8.8.1
  device_preview: ^0.4.5
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat-Bold.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
